<a href="https://colab.research.google.com/github/JeffersonEvangelista/JeffersonEvangelista/blob/main/Snoopy_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## P1

In [ ]:
import bs4 as bs
# pip install bs4
import urllib.request
import re
import nltk
import numpy as np
import random
import string


In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
!pip install spacy --upgrade

In [ ]:
import spacy
spacy.__version__

'3.8.7'

In [ ]:
!python3 -m spacy download pt

⚠ As of spaCy v3.0, shortcuts like 'pt' are deprecated. Please use the
full pipeline package name 'pt_core_news_sm' instead.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 69.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
urls = [
    'https://pt.wikipedia.org/wiki/Snoopy',                              # Personagem principal :contentReference[oaicite:1]{index=1}
    'https://pt.wikipedia.org/wiki/Snoopy%2C_Come_Home%21',             # Filme de 1972 :contentReference[oaicite:2]{index=2}
    'https://pt.wikipedia.org/wiki/Snoopy_no_Espa%C3%A7o',              # Série “Snoopy no Espaço” :contentReference[oaicite:3]{index=3}
    'https://pt.wikipedia.org/wiki/The_Snoopy_Show',                    # “The Snoopy Show” :contentReference[oaicite:4]{index=4}
    'https://pt.wikipedia.org/wiki/The_Charlie_Brown_and_Snoopy_Show'   # “The Charlie Brown and Snoopy Show” :contentReference[oaicite:5]{index=5}
]

todos_paragrafos = []

In [ ]:
for url in urls:
    try:
        dados = urllib.request.urlopen(url)
        dados = dados.read()
        dados_html = bs.BeautifulSoup(dados, 'lxml')
        paragrafos = dados_html.find_all('p')
        todos_paragrafos.extend(paragrafos)
    except Exception as e:
        print(f"Erro ao processar {url}: {str(e)}")

In [ ]:
num_paragrafos_total = len(todos_paragrafos)
print (num_paragrafos_total)

48


In [ ]:
print(todos_paragrafos[20].text)

O cãozinho beagle Snoopy vive uma vida relativamente tranquila com seu dono Charlie Brown, indo costumeiramente à praia com sua amiga Patty Pimentinha onde brincam e nadam na água do mar alegremente. Contudo, sua vida livre causa irritação em Charlie Brown que percebe que Snoopy está cada vez mais se tornando "independente", saindo e voltando para casa no horário que quiser enquanto Charlie Brown prepara seu jantar todos os dias cada vez mais furioso com isso. Um dia, Snoopy é barrado de entrar na praia por conta de uma nova restrição que proibia cães no local, fazendo-o escrever uma carta para o seu "editor" reclamando sobre a restrição; Patty, que havia marcado de fazer um piquenique com Snoopy na praia, pensa que o cãozinho "deu-lhe um bolo" e se enfurece.



In [ ]:
conteudo = ''
for p in todos_paragrafos:
    conteudo += p.text + ' '

In [ ]:
conteudo

'Snoopy é o beagle[1] de estimação de Charlie Brown na tira em quadrinhos Peanuts, criada por Charles Schulz.\n Snoopy aparece pela primeira vez em 4 de Outubro de 1950. Embora a primeira tirinha tenha sido apresentada em 2 de outubro do mesmo ano. Schulz originalmente ia chamar o cão de "Sniffy",  até que descobriu que esse nome já era usado em outra tirinha . Snoopy foi durante dois anos uma figura silenciosa, agindo como um cão real (caminhava sobre as quatro patas), mas, em 19 de Outubro de 1952, ele verbalizou os seus pensamentos aos leitores pela primeira vez através de balões; Snoopy tinha também a capacidade de entender tudo o que as restantes personagens dos Peanuts, com quem interagia, diziam. Schulz, após esta data, passou a incluir essas características na sua banda desenhada.\n Snoopy é um cão extrovertido com complexo de Walter Mitty, com muitas virtudes. A maior parte delas não são reais, mas sonhos que fazem parte do seu mundo de fantasia, que aparecem quando Snoopy dor

In [ ]:
conteudo = conteudo.lower()
conteudo

'snoopy é o beagle[1] de estimação de charlie brown na tira em quadrinhos peanuts, criada por charles schulz.\n snoopy aparece pela primeira vez em 4 de outubro de 1950. embora a primeira tirinha tenha sido apresentada em 2 de outubro do mesmo ano. schulz originalmente ia chamar o cão de "sniffy",  até que descobriu que esse nome já era usado em outra tirinha . snoopy foi durante dois anos uma figura silenciosa, agindo como um cão real (caminhava sobre as quatro patas), mas, em 19 de outubro de 1952, ele verbalizou os seus pensamentos aos leitores pela primeira vez através de balões; snoopy tinha também a capacidade de entender tudo o que as restantes personagens dos peanuts, com quem interagia, diziam. schulz, após esta data, passou a incluir essas características na sua banda desenhada.\n snoopy é um cão extrovertido com complexo de walter mitty, com muitas virtudes. a maior parte delas não são reais, mas sonhos que fazem parte do seu mundo de fantasia, que aparecem quando snoopy dor

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [ ]:
lista_sentencas = nltk.sent_tokenize(conteudo)

In [ ]:
lista_sentencas

['snoopy é o beagle[1] de estimação de charlie brown na tira em quadrinhos peanuts, criada por charles schulz.',
 'snoopy aparece pela primeira vez em 4 de outubro de 1950. embora a primeira tirinha tenha sido apresentada em 2 de outubro do mesmo ano.',
 'schulz originalmente ia chamar o cão de "sniffy",  até que descobriu que esse nome já era usado em outra tirinha .',
 'snoopy foi durante dois anos uma figura silenciosa, agindo como um cão real (caminhava sobre as quatro patas), mas, em 19 de outubro de 1952, ele verbalizou os seus pensamentos aos leitores pela primeira vez através de balões; snoopy tinha também a capacidade de entender tudo o que as restantes personagens dos peanuts, com quem interagia, diziam.',
 'schulz, após esta data, passou a incluir essas características na sua banda desenhada.',
 'snoopy é um cão extrovertido com complexo de walter mitty, com muitas virtudes.',
 'a maior parte delas não são reais, mas sonhos que fazem parte do seu mundo de fantasia, que apare

In [ ]:
len(lista_sentencas)

153

In [ ]:
type(lista_sentencas)

list

In [ ]:
lista_sentencas[10]

'schulz, numa entrevista em 1997, disse o seguinte acerca do carácter do snoopy: "ele tem que sair do seu mundo de fantasia para sobreviver.'

In [ ]:
pln = spacy.load('pt_core_news_sm')

In [ ]:
stop_words = spacy.lang.pt.stop_words.STOP_WORDS


In [ ]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def preprocessamento(texto):

    texto = re.sub(r"https?://[A-Za-z0-9./]+", ' ', texto)

    texto = re.sub(r" +", ' ', texto)

    documento = pln(texto)
    lista = []
    for token in documento:
      lista.append(token.lemma_)

    lista = [palavra for palavra in lista if palavra not in stop_words and palavra not in string.punctuation]
    lista = ' '.join([str(elemento) for elemento in lista if not elemento.isdigit()])

    return lista

In [ ]:
texto_teste = 'https://fateczonasul.edu.br/' + lista_sentencas[85]
texto_teste

'https://fateczonasul.edu.br/durante a viagem, snoopy e woodstock tentam viajar de ônibus, mas o cão é chutado pra fora do veículo, mais uma vez por conta de uma proibição contra cães.'

In [ ]:
resultado= preprocessamento(texto_teste)
resultado

'  viagem snoopy woodstock viajar ônibus cão chutar pra de o veículo conta proibição cão'

In [ ]:
lista_sentencas_preprocessada = []
for i in range(len(lista_sentencas)):
  lista_sentencas_preprocessada.append(preprocessamento(lista_sentencas[i]))

In [ ]:
for _ in range(5):
    i = random.randint(0, len(lista_sentencas) - 1)
    print(lista_sentencas[i])
    print(lista_sentencas_preprocessada[i])

produzido pela cinema center films (sendo a última produção desse estúdio), lee mendelson/bill melendez productions e sopwith productions, foi lançado nos cinemas americanos em 9 de agosto de 1972 pela national general pictures.
produzir por o cinema center films produção de esse estúdio Lee mendelson bill melendez productions Sopwith Productions lançar em o cinema americano agosto por o national general pictur
snoopy e lila finalmente se reencontram e o cão passa a fazer companhia para a menina, embora ainda precise se esconder dos enfermeiros.
snoopy lila finalmente reencontr cão passar companhia menina preciser esconder de o enfermeiro
durante a viagem, snoopy e woodstock tentam viajar de ônibus, mas o cão é chutado pra fora do veículo, mais uma vez por conta de uma proibição contra cães.
durante viagem snoopy woodstock viajar ônibus cão chutar pra de o veículo conta proibição cão
antes de serem vendidos, snoopy e seus irmãos e irmãs formavam uma banda e um por um, cada um foi vendi

In [ ]:
textos_boas_vindas_entrada = {'hey', 'ola', 'oi', 'eae'}
textos_boas_vindas_respostas = {'hey', 'ola', 'oi', 'eae', 'bom dia', 'como vc vai?', 'salve'}

In [ ]:
'ola'.split()

['ola']

In [ ]:
def responder_saudacao(texto):
  for palavra in texto.split():
    if palavra.lower() in textos_boas_vindas_entrada:
      return random.choise(textos_boas_vindas_respostas)

In [ ]:
responder_saudacao('ola, como vc vai?')

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

frases_teste = lista_sentencas_preprocessada[:3]
frases_teste

['snoopy beagle[1 estimação charlie brown em o tira quadrinho peanuts criar charle Schulz',
 'snoopy aparecer por o outubro tirinha apresentar outubro de o ano',
 'Schulz originalmente chamar cão sniffy descobrir nome outro tirinha']

In [ ]:
frases_teste.append(frases_teste[0])
frases_teste


['snoopy beagle[1 estimação charlie brown em o tira quadrinho peanuts criar charle Schulz',
 'snoopy aparecer por o outubro tirinha apresentar outubro de o ano',
 'Schulz originalmente chamar cão sniffy descobrir nome outro tirinha',
 'snoopy beagle[1 estimação charlie brown em o tira quadrinho peanuts criar charle Schulz']

In [ ]:
vetores_palavras = TfidfVectorizer()
palavras_vetorizadas = vetores_palavras.fit_transform(frases_teste)

palavras_vetorizadas

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 41 stored elements and shape (4, 26)>

In [ ]:
print(vetores_palavras.get_feature_names_out())

['ano' 'aparecer' 'apresentar' 'beagle' 'brown' 'chamar' 'charle'
 'charlie' 'criar' 'cão' 'de' 'descobrir' 'em' 'estimação' 'nome'
 'originalmente' 'outro' 'outubro' 'peanuts' 'por' 'quadrinho' 'schulz'
 'sniffy' 'snoopy' 'tira' 'tirinha']


In [ ]:
len(vetores_palavras.get_feature_names_out())

26

In [ ]:
print(vetores_palavras.vocabulary_)

{'snoopy': 23, 'beagle': 3, 'estimação': 13, 'charlie': 7, 'brown': 4, 'em': 12, 'tira': 24, 'quadrinho': 20, 'peanuts': 18, 'criar': 8, 'charle': 6, 'schulz': 21, 'aparecer': 1, 'por': 19, 'outubro': 17, 'tirinha': 25, 'apresentar': 2, 'de': 10, 'ano': 0, 'originalmente': 15, 'chamar': 5, 'cão': 9, 'sniffy': 22, 'descobrir': 11, 'nome': 14, 'outro': 16}


In [ ]:
print(vetores_palavras.idf_)

[1.91629073 1.91629073 1.91629073 1.51082562 1.51082562 1.91629073
 1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073 1.91629073
 1.51082562 1.91629073 1.51082562 1.22314355 1.91629073 1.22314355
 1.51082562 1.51082562]


In [ ]:
palavras_vetorizadas.todense()

matrix([[0.        , 0.        , 0.        , 0.29733922, 0.29733922,
         0.        , 0.29733922, 0.29733922, 0.29733922, 0.        ,
         0.        , 0.        , 0.29733922, 0.29733922, 0.        ,
         0.        , 0.        , 0.        , 0.29733922, 0.        ,
         0.29733922, 0.24072172, 0.        , 0.24072172, 0.29733922,
         0.        ],
        [0.31577018, 0.31577018, 0.31577018, 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.31577018, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.63154037, 0.        , 0.31577018,
         0.        , 0.        , 0.        , 0.20155202, 0.        ,
         0.24895684],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.35291425, 0.        , 0.        , 0.        , 0.35291425,
         0.        , 0.35291425, 0.        , 0.        , 0.35291425,
         0.35291425, 0.35291425, 0.        , 0.        , 0.

In [ ]:
palavras_vetorizadas.todense().shape

(4, 26)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
palavras_vetorizadas[0].todense()

matrix([[0.        , 0.        , 0.        , 0.29733922, 0.29733922,
         0.        , 0.29733922, 0.29733922, 0.29733922, 0.        ,
         0.        , 0.        , 0.29733922, 0.29733922, 0.        ,
         0.        , 0.        , 0.        , 0.29733922, 0.        ,
         0.29733922, 0.24072172, 0.        , 0.24072172, 0.29733922,
         0.        ]])

In [ ]:
cosine_similarity(palavras_vetorizadas[0], palavras_vetorizadas[1])

array([[0.04851795]])

In [ ]:
similiaridade = cosine_similarity(palavras_vetorizadas[0], palavras_vetorizadas)
similiaridade

array([[1.        , 0.04851795, 0.05422512, 1.        ]])

In [ ]:
def responder(texto_usuario):
  resposta_chatbot = ''
  lista_sentencas_preprocessada.append(texto_usuario)

  tfidf = TfidfVectorizer()
  palavras_vetorizadas = tfidf.fit_transform(lista_sentencas_preprocessada)

  similaridade = cosine_similarity(palavras_vetorizadas[-1], palavras_vetorizadas)

  indice_sentenca = similaridade.argsort()[0][-2]
  vetor_similar = similaridade.flatten()
  vetor_similar.sort()
  vetor_encontrado = vetor_similar[-2]

  if (vetor_encontrado == 0):
    resposta_chatbot = resposta_chatbot + 'Desculpe, mas não entendi!'
    return resposta_chatbot
  else:
    resposta_chatbot = resposta_chatbot + lista_sentencas[indice_sentenca]
    return resposta_chatbot

In [ ]:
continuar = True
print('Olá, sou um chatbot e vou responder perguntas sobre o Snoopy: ')
while (continuar == True):
  texto_usuario = input()
  texto_usuario = texto_usuario.lower()
  if (texto_usuario != 'sair'):
    if (responder_saudacao(texto_usuario) != None):
      print('Chatbot: ' + responder_saudacao(texto_usuario))
    else:
      print('Chatbot: ')
      print(responder(preprocessamento(texto_usuario)))
      lista_sentencas_preprocessada.remove(preprocessamento(texto_usuario))
  else:
    continuar = False
    print('Chatbot: Até breve!')

Olá, sou um chatbot e vou responder perguntas sobre o Snoopy: 
historia do personagem?
Chatbot: 
um dos primeiros desenvolvimentos do personagem de snoopy foi a sua tendência para dormir no telhado da sua casa, em vez de dentro dela.
qual idade
Chatbot: 
Desculpe, mas não entendi!
que ano foi criado?
Chatbot: 
ao longo dos anos, foi revelado que snoopy nasceu e foi criado na fazenda de cães daisy hill  .
